### ISSUE TITLE
Running Issue

### ISSUE THREAD

**Issue by atrivialpursuit** [cageyoko/CTC-Attention-Mispronunciation#9]
Hi, I have tried to run both models and get the same error during Acoustic Model (CTC) Training

Start training epoch: 1, learning_rate: 0.00100
Epoch = 1, step = 50, cur_loss = 93.3737, total_loss = 93.3737, total_wer = 0.7058
Epoch 1 Train done, total_loss: 72.1015, total_wer: 0.5574
Traceback (most recent call last):
  File "steps/train_ctc.py", line 263, in <module>
    main(conf)
  File "steps/train_ctc.py", line 192, in main
    acc, dev_loss = run_epoch(count, model, dev_loader, loss_fn, device, optimizer=None, print_every=opts.verbose_step, is_training=False)
  File "steps/train_ctc.py", line 70, in run_epoch
    average_loss = total_loss / (i+1)
UnboundLocalError: local variable 'i' referenced before assignment

The only changes I have made to your work were:
- Dataset and kaldi root paths
- Changed (cuda:1) to (cuda:0) as I am only using 1 GPU

Do you have any ideas as to where am I going wrong?

Thanks

**Comment by atrivialpursuit** [comment]
Path error. Resolved
